#!/usr/bin/env python3
"""Build a draft EMOS/ordinary-app review bundle. Never touch physical media.

The maintained source is prepared and built only by the repository wrappers.
The smoke binary shares this bundle's EMOS identity; it is an ordinary MOS
application and does not implement an alternate firmware or transport.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
SMOKE = ROOT / "projects/boot-smoke"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--builder", type=Path, default=ROOT.parent / "mos-agondev")
    parser.add_argument("--fab-root", type=Path, required=True)
    args = parser.parse_args()
    output = args.output.absolute()
    if output.exists() or output.is_symlink():
        parser.error("output must be a new directory")
    builder = args.builder.resolve(strict=True)
    fab = args.fab_root.resolve(strict=True)
    toolchain = (builder / "toolchains/agondev").resolve(strict=True)
    identity_text = (ROOT / "port/identity.mk").read_text()
    def identity_value(key: str) -> str:
        match = re.search(rf"^{key}\s*:=\s*(\S+)\s*$", identity_text, re.MULTILINE)
        if not match:
            raise ValueError(f"missing literal {key}")
        return match.group(1)
    identity = identity_value("EMOS_SOURCE_IDENTITY")
    status = identity_value("EMOS_ARTIFACT_STATUS")
    if status != "draft":
        parser.error("this wrapper prepares draft review builds only")
    now = datetime.now(timezone.utc)
    build_id = identity + now.strftime("-b%Y-%m-%d-%H-%M-%SZ")
    output.mkdir(parents=True)
    (output / "build-id.txt").write_text(build_id + "\n")
    worktree = builder / "projects/mos-port" / ("worktree-" + build_id)
    environment = dict(os.environ, EMOS_BUILD_ID=build_id)
    def run(argv: list[str], log_name: str, cwd: Path = ROOT) -> None:
        print(f"{log_name}: {' '.join(argv[:3])}", flush=True)
        with (output / log_name).open("w") as log:
            log.write(json.dumps(argv) + "\n")
            log.flush()
            result = subprocess.run(argv, cwd=cwd, env=environment,
                                    stdout=log, stderr=subprocess.STDOUT)
        if result.returncode:
            print((output / log_name).read_text()[-7000:], file=sys.stderr)
            raise SystemExit(f"{log_name} failed ({result.returncode}); see {output}")
    run([str(builder / ".venv/bin/python"), str(builder / "scripts/prepare_mos_worktree.py"),
         "--upstream", str(ROOT), "--destination", str(worktree)], "prepare.log")
    make_args = ["make", f"PYTHON={sys.executable}", f"MOS_AGONDEV_ROOT={builder}",
                 f"MOS_WORKTREE={worktree}", f"AGONDEV_TOOLCHAIN={toolchain}",
                 f"FAB_ROOT={fab}", f"EMOS_BUILD_ID={build_id}"]
    run(make_args + ["qualify"], "qualify.log")
    run(make_args + ["linked-check"], "linked-check.log")
    header = SMOKE / "build/build_identity.h"
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text("// Generated by prepare_boot_review.py; do not edit.\n"
                      f'#define EMOS_BUILD_ID "{build_id}"\n'
                      f'#define EMOS_ARTIFACT_STATUS "{status}"\n')
    run(["make", "clean"], "smoke-clean.log", SMOKE)
    run(["make", f"AGONDEV_TOOLCHAIN={toolchain}", "all"], "smoke-build.log", SMOKE)
    outputs = []
    for source, name, role in [
        (builder / "projects/mos-port/bin/MOS.bin", build_id + ".bin", "firmware"),
        (builder / "projects/mos-port/bin/MOS.elf", build_id + ".elf", "linked_firmware"),
        (builder / "projects/mos-port/bin/MOS.map", build_id + ".map", "firmware_map"),
        (SMOKE / "bin/EMBOOT.bin", build_id + "-boot-smoke.bin", "smoke_program"),
    ]:
        target = output / name
        shutil.copyfile(source, target)
        outputs.append({"filename": name, "role": role, "size_bytes": target.stat().st_size,
                        "sha256": digest(target)})
    tracked = git(ROOT, "ls-files", "-z").split("\0")
    source_hashes = {name: digest(ROOT / name) for name in tracked if name and (ROOT / name).is_file()}
    # Include the new review tools/application before their first commit.
    for path in [Path(__file__), ROOT / "scripts/review_boot.py", ROOT / "requirements-dev.txt",
                 *sorted((SMOKE / "src").glob("*.c")), SMOKE / "Makefile"]:
        source_hashes[str(path.relative_to(ROOT))] = digest(path)
    builder_hashes = {name: digest(builder / name)
                      for name in git(builder, "ls-files", "-z").split("\0")
                      if name and (builder / name).is_file()}
    manifest = {
        "schema_version": 1,
        "build": {"artifact_id": "agon-emos", "source_identity": identity,
                  "build_id": build_id, "status": status, "variant": None,
                  "created_at": now.strftime("%Y-%m-%dT%H:%M:%SZ")},
        "provenance": {"repository": "https://github.com/bgates747/agon-emos.git",
                       "commit": git(ROOT, "rev-parse", "HEAD"),
                       "dirty": bool(git(ROOT, "status", "--porcelain")),
                       "builder_commit": git(builder, "rev-parse", "HEAD"),
                       "builder_dirty": bool(git(builder, "status", "--porcelain")),
                       "builder_source_sha256": builder_hashes,
                       "source_sha256": source_hashes,
                       "preparation_sha256": digest(worktree / ".mos-agondev-worktree.json"),
                       "compiler_sha256": digest(toolchain / "bin/ez80-none-elf-clang")},
        "outputs": outputs,
        "notes": ["Draft review build; no physical deployment or qualification claim.",
                  "Registered linked UART and parallel checks retained.",
                  "BOOT smoke is an ordinary MOS application in the same identified build bundle."]}
    (output / "build-manifest.yaml").write_text(yaml.safe_dump(manifest, sort_keys=False))
    for kind in ("stock", "emos"):
        sdcard = output / (kind + "-sdcard")
        (sdcard / "bin").mkdir(parents=True)
        (sdcard / "emos-boot").mkdir()
        shutil.copyfile(output / outputs[3]["filename"], sdcard / "bin/EMBOOT.BIN")
        (sdcard / "emos-boot/check.txt").write_bytes(b"EMOS SD CHECK\r\n")
        commands = []
        if kind == "emos": commands.append("EMOS STATUS")
        commands.extend(["LOAD /bin/EMBOOT.BIN", "RUN"])
        if kind == "emos": commands.append("EMOS STATUS")
        (sdcard / "autoexec.txt").write_bytes(("\r\n".join(commands) + "\r\n").encode())
    run([sys.executable, str(ROOT / "projects/emos/verify_runtime.py"),
         "--fab-root", str(fab), "--firmware", str(output / outputs[0]["filename"]),
         "--manifest", str(output / "build-manifest.yaml")], "emos-runtime.log")
    print(f"Review bundle: {output}\nBuild: {build_id}")


if __name__ == "__main__":
    main()
