#!/usr/bin/env python3
"""Build a committed, identified SD service; never deploy or touch hardware."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import yaml

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "projects/sdserve"

def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--toolchain", type=Path, required=True)
    a = p.parse_args()
    output = a.output.absolute()
    toolchain = a.toolchain.resolve(strict=True)
    identity = json.loads((APP / "identity.json").read_text())
    if git("status", "--porcelain"):
        p.error("identified candidates require clean committed source")
    commit = git("rev-parse", "HEAD")
    sources = {n: sha(ROOT/n) for n in git("ls-files", "-z").split("\0")
               if n and (ROOT/n).is_file()}
    now = datetime.now(timezone.utc)
    build_id = identity["source_identity"] + now.strftime("-b%Y-%m-%d-%H-%M-%SZ")
    output.mkdir(parents=True, exist_ok=False)
    header = APP / "build/build_identity.h"
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text("// Generated by prepare_sdserve.py; do not edit.\n"
                      f'#define SDSERVE_BUILD_ID "{build_id}"\n'
                      f'#define SDSERVE_STATUS "{identity["status"]}"\n')
    with (output/"build.log").open("w") as log:
        for target in ("clean", "all"):
            subprocess.run(["make", f"AGONDEV_TOOLCHAIN={toolchain}",
                            "SDSERVE_IDENTIFIED_BUILD=1", target], cwd=APP,
                           stdout=log, stderr=subprocess.STDOUT, check=True)
    if git("status", "--porcelain") or git("rev-parse", "HEAD") != commit:
        raise RuntimeError("source changed during candidate build")
    source = APP/"bin/sdserve.bin"
    if build_id.encode() not in source.read_bytes():
        raise RuntimeError("binary does not contain expected identity")
    target = output/(build_id+".bin")
    shutil.copyfile(source, target)
    manifest = {"schema_version": 1,
                "build": dict(identity, build_id=build_id, created_at=now.isoformat()),
                "provenance": {"commit": commit, "dirty": False, "source_sha256": sources,
                               "compiler_sha256": sha(toolchain/"bin/ez80-none-elf-clang")},
                "outputs": [{"filename": target.name, "role": "application",
                             "sha256": sha(target), "size_bytes": target.stat().st_size}],
                "notes": ["Install with canonical filename sdserve.bin.",
                          "Candidate build only; physical qualification pending."]}
    (output/"build-manifest.yaml").write_text(yaml.safe_dump(manifest, sort_keys=False))
    print(build_id, target)

if __name__ == "__main__":
    main()
