#!/usr/bin/env python3
"""Check a frozen draft bundle and create isolated stock/EMOS review profiles.

No physical device or removable medium is opened. Profiles contain only the
ordinary smoke; the existing fake-mode regression has separate media.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "projects/emos"))
from verify_runtime import identity_from_manifest

STOCK_SHA = "d564243283972690933a4554296ad6202ca4ef54572279533a942960846bebae"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def make_profile(profile: Path, firmware: Path, mos_map: Path, sdcard: Path,
                 fab: Path, *, runtime: Path | None = None,
                 peer: Path | None = None,
                 mutable_names: tuple[str, ...] = ("keyboard-state.bin",)) -> None:
    profile.mkdir()
    binary = (runtime or fab) / "target/release/fab-agon-emulator"
    vdp = fab / "firmware/vdp_platform.so"
    raw = profile / "fab-agon-emulator.bin"
    raw.symlink_to(binary)
    mutable = {str(sdcard / name) for name in mutable_names} if peer else set()
    inputs = [raw, firmware, mos_map, vdp, *sorted(p for p in sdcard.rglob("*")
              if p.is_file() and str(p) not in mutable)]
    if peer:
        inputs += [peer, runtime / 'runtime-inputs.json']
    hashes = {str(p): digest(p) for p in inputs}
    # This review intentionally substitutes identified EMOS for the stock MOS
    # release. Pin both selections and all media; never silently fall back.
    launcher = profile / "fab-agon-emulator"
    launcher.write_text(f'''#!{sys.executable}
# Generated by agon-emos scripts/review_boot.py; do not edit.
import hashlib, os, pathlib, subprocess, sys, tempfile
hashes = {hashes!r}
mutable = {mutable!r}
if sys.argv[1:] not in ([], ["--check"]):
    raise SystemExit("This frozen profile accepts only --check or no arguments")
for name, expected in hashes.items():
    path = pathlib.Path(name)
    if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != expected:
        raise SystemExit("Missing or changed profile input: " + name)
sdcard = pathlib.Path({str(sdcard)!r})
expected_media = {{name for name in hashes if name.startswith(str(sdcard) + "/")}}
actual_media = {{str(p) for p in sdcard.rglob("*") if p.is_file()}} - mutable
if actual_media != expected_media or any(p.is_symlink() for p in sdcard.rglob("*")):
    raise SystemExit("Review media inventory changed")
if sys.argv[1:] == ["--check"]:
    print("Frozen review profile verified")
    raise SystemExit(0)
sdl = pathlib.Path.home() / ".local/lib"
if (sdl / "libSDL3.so.0").is_file():
    os.environ["LD_LIBRARY_PATH"] = str(sdl) + os.pathsep + os.environ.get("LD_LIBRARY_PATH", "")
with tempfile.TemporaryDirectory(prefix="emos-boot-fab-") as cwd:
    if {bool(peer)!r}:
        command = [sys.executable, {str(peer)!r}, "--emulator", {str(raw)!r},
            "--firmware", {str(firmware)!r}, "--vdp", {str(vdp)!r},
            "--sdcard", str(sdcard), "--graphical", "--output",
            {str(profile/'last-peer.json')!r}]
    else:
        command = [{str(raw)!r}, "--mos", {str(firmware)!r},
            "--vdp", {str(vdp)!r}, "--sdcard", str(sdcard),
            "--renderer", "sw", "--verbose", "--zero"]
    raise SystemExit(subprocess.call(command, cwd=cwd))
''')
    launcher.chmod(0o755)
    (profile / "profile-inputs.json").write_text(json.dumps(hashes, indent=2) + "\n")
    subprocess.run([str(launcher), "--check"], cwd=profile, check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", type=Path, required=True)
    parser.add_argument("--fab-root", type=Path, required=True)
    parser.add_argument("--output", type=Path,
                        help="new review directory (default: <bundle>/review)")
    args = parser.parse_args()
    bundle = args.bundle.resolve(strict=True)
    fab = args.fab_root.resolve(strict=True)
    manifest = bundle / "build-manifest.yaml"
    record = yaml.safe_load(manifest.read_text())
    outputs = {item["role"]: bundle / item["filename"] for item in record["outputs"]}
    for item in record["outputs"]:
        if digest(bundle / item["filename"]) != item["sha256"]:
            raise SystemExit("Changed bundle output: " + item["filename"])
    identity = identity_from_manifest(manifest, outputs["firmware"])
    stock = fab / "firmware/mos_platform.bin"
    if digest(stock) != STOCK_SHA:
        raise SystemExit("Stock reference is not the selected MOS v3.0.2 release")
    review = args.output.absolute() if args.output else bundle / "review"
    review.mkdir()  # Refuse to overwrite an earlier review.
    (review / "review-inputs.json").write_text(json.dumps({
        "review_script_sha256": digest(Path(__file__)),
        "build_manifest_sha256": digest(manifest),
        "cli_sha256": digest(fab / "target/release/agon-cli-emulator"),
    }, indent=2) + "\n")
    profiles = review / "profiles"
    profiles.mkdir()
    cli = fab / "target/release/agon-cli-emulator"
    for kind, firmware, mos_map in (
        ("stock", stock, fab / "firmware/mos_platform.map"),
        ("emos", outputs["firmware"], outputs["firmware_map"]),
    ):
        sdcard = bundle / (kind + "-sdcard")
        for negative in (False, True):
            with tempfile.TemporaryDirectory(prefix="emos-smoke-") as temporary:
                media = Path(temporary) / "sdcard"
                shutil.copytree(sdcard, media)
                if negative:
                    (media / "emos-boot/check.txt").write_bytes(b"incorrect\r\n")
                result = subprocess.run([str(cli), "--mos", str(firmware),
                    "--sdcard", str(media), "--unlimited-cpu", "--zero"],
                    input=b"echo BOOT REVIEW PROMPT RETURNED\n", stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT, timeout=30)
                label = kind + ("-bad-sd" if negative else "-smoke")
                (review / (label + ".log")).write_bytes(result.stdout)
                lines = [line.strip(b"\x00\x80 ") for line in
                         result.stdout.replace(b"\r", b"").splitlines()]
                if result.returncode or b"BOOT REVIEW PROMPT RETURNED" not in lines:
                    raise SystemExit(label + ": emulator failed or prompt return absent")
                expected = [b"BOOT SMOKE FAIL: SD contents"] if negative else [
                    b"BOOT SMOKE SD PASS", b"BOOT SMOKE CLOCK PASS",
                    b"BOOT SMOKE PASS - returning to MOS"]
                if any(line not in lines for line in expected):
                    raise SystemExit(label + ": missing expected smoke output")
                if negative and b"BOOT SMOKE PASS - returning to MOS" in lines:
                    raise SystemExit(label + ": false smoke pass")
                if not negative and b"BOOT SMOKE FAIL:" in result.stdout:
                    raise SystemExit(label + ": smoke failure")
                smoke_identity = (f"EMOS BOOT SMOKE {record['build']['build_id']} "
                                  f"({record['build']['status']})").encode("ascii")
                if lines.count(smoke_identity) != 1:
                    raise SystemExit(label + ": unexpected smoke identity")
                if kind == "emos":
                    # RUN propagates the application's nonzero result, so a
                    # bad SD fixture stops autoexec before the final STATUS.
                    statuses = 1 if negative else 2
                    for line, count in ((identity, statuses + 1),
                        (b"EMOS v1: Legacy, registry 0, generation 0", statuses),
                        (b"VDU route 0, EDU inactive, adapter unavailable, mode generation 0", statuses)):
                        if lines.count(line) != count:
                            raise SystemExit(label + ": unexpected EMOS identity or state")
                print(label + ": PASS", flush=True)
        make_profile(profiles / kind, firmware, mos_map, sdcard, fab)
    print(f"Human review: cd {profiles / 'emos'} && ./fab-agon-emulator")


if __name__ == "__main__":
    main()
